FROM pytorch/pytorch:1.10.0-cuda11.3-cudnn8-runtime
RUN pip install detectron2 -f https://dl.fbaipublicfiles.com/detectron2/wheels/cu113/torch1.10/index.html && \
    pip install pandas scikit-learn opencv-python